version: '3'

services:

  knowledge-journies-service:
    image: debezium/postgres:13-alpine
    environment:
      - POSTGRES_DATABASE=knowledge_journy_dev
      - POSTGRES_USER=knowledge_journy_dev
      - POSTGRES_PASSWORD=knowledge_journy_dev
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/data/db

volumes:
  postgres-data:
